services:
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: postgres-eventstec
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=eventstec
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
